# Generated by Django 3.1.5 on 2021-01-22 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('kok', models.CharField(max_length=20)),
                ('totalPeople', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Housemate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', editable=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HousemateEats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('eetMee', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0)),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cook')),
            ],
        ),
    ]
