# Generated by Django 3.1.5 on 2021-01-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemate',
            name='eetmee',
            field=models.BooleanField(default=False),
        ),
    ]
