# Generated by Django 3.1.5 on 2021-01-22 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_housemate_eetmee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housemate',
            old_name='eetmee',
            new_name='eetMee',
        ),
    ]
