# Generated by Django 3.1.5 on 2021-01-25 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_cook_totalpeople'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cook',
            name='amount',
        ),
    ]
