# Generated by Django 3.1.5 on 2021-01-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210122_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bedrag', models.FloatField()),
                ('kok', models.CharField(choices=[('Quinty', 'Quinty'), ('Wolf', 'Wolf'), ('Linda', 'Linda'), ('Robbert', 'Robbert'), ('Cato', 'Cato'), ('Daan', 'Daan'), ('Louise', 'Louise'), ('Thom', 'Thom')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='housemate',
            name='eetMee',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0),
        ),
    ]
