# Generated by Django 3.1.5 on 2021-01-26 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_cook_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('people', models.IntegerField()),
                ('cook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.cook')),
            ],
        ),
    ]
