# Generated by Django 3.1.5 on 2021-01-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210122_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('bedrag', models.FloatField()),
                ('kok', models.CharField(choices=[('Quinty', 'Quinty'), ('Wolf', 'Wolf'), ('Linda', 'Linda'), ('Robbert', 'Robbert'), ('Cato', 'Cato'), ('Daan', 'Daan'), ('Louise', 'Louise'), ('Thom', 'Thom')], max_length=20)),
                ('totalPeople', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HousemateCook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('eetMee', models.BooleanField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Date',
        ),
        migrations.RemoveField(
            model_name='housemate',
            name='eetMee',
        ),
    ]
