# Generated by Django 3.1.5 on 2021-01-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210122_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cook',
            old_name='bedrag',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='housematecook',
            name='eetMee',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0),
        ),
    ]
