# Generated by Django 3.1.5 on 2021-01-22 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210122_1955'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HousemateCook',
            new_name='HousemateEats',
        ),
    ]
